### ISSUE TITLE
Building MLIR-Graph

### ISSUE THREAD

**Issue by chelini** [metagraph-dev/mlir-graphblas#90]
Dear All,
I am excited about the project. Do you have any documentation other than the website that illustrates the graphs blas dialect in more detail? How do you plan to evolve it? Currently, it seems a simple addition on top of the sparse dialect, already available in MLIR.

In addition, I am not able to install the software with build.py. Get the error message:

```
Traceback (most recent call last):
  File "build.py", line 114, in <module>
    build_graphblas_opt(args.build_clean)
  File "build.py", line 68, in build_graphblas_opt
    (PYTHONPATH,) = site.getsitepackages()
ValueError: too many values to unpack (expected 1)

```
Any tip on how to solve it?

**Comment by seibert** [comment]
Hi, sorry for the delay in responding.  I'm glad you are interested in this project!  You happened to catch us around some vacations and completing some end-of-quarter documentation.

This are still pretty rough right now as we are at the early stages, but you can read about the dialect more here: https://mlir-graphblas.readthedocs.io/en/latest/dialect/index.html

Because a lot of MLIR is under frequent updates, this code requires a specific development commit of MLIR that we update periodically.  One way to avoid building from source is to install our development builds using conda:

```
conda create -n mlir_grb -c conda-forge -c metagraph/label/dev -c metagraph python=3.8 mlir-graphblas notebook
```

We should also setup a Binder environment to make it easier for people to try stuff out.

**Comment by seibert** [comment]
Bigger picture, we want to implement graph algorithms in MLIR and optimize them (both the individual algorithms, as well as higher level fusion of operations in metagraph).  We're tracking (and very excited about) the sparse tensor work that Aart Bik is doing, but that work isn't complete enough yet for our use.  So we are temporarily having to implement the basic linear algebra operations on sparse tensors we need using the `scf` dialect.  Eventually, we will swap out that lowering to use the `linalg` dialect when it can generate sparse tensor output (which it cannot do in general yet).

GraphBLAS is also a little different than traditional sparse linear algebra, as operations can use a configurable semiring (rather than the traditional definitions of `+` and `*`).  For this reason, GraphBLAS doesn't automatically assume that `0` is equivalent to a missing value, since that depends on the semiring being used.  We're not sure yet how we will ensure that the MLIR sparse `linalg` has this level of flexibility, but that is what we are aiming for.

**Comment by seibert** [comment]
Also, the error you found looks like a mistaken assumption on our part that there would be a single directory for site packages.  I'll open a separate issue for that.

**Comment by chelini** [comment]
@seibert Thanks a lot and sorry for the latency. I was able to build the project, and I am currently looking into it.

**Comment by chelini** [comment]
@seibert me again, I have a small patch that I would like to submit. What would be the process? What kind of code format should I use? It seems that the style you use in the MLIR part is not formatted using the llvm style as MLIR is. Thanks.

**Comment by seibert** [comment]
Go ahead and open a PR.  Our lack of LLVM style is not intentional, so feel free to follow LLVM style if you want.  I need to implement a code formatter for C++ (like astyle) where I can select the LLVM style, similar to how we use black for formatting our Python code.

**Comment by chelini** [comment]
@seibert do you have any documentation on the lowering strategy? I miss a bit of context on what is expected as result of the lowering step. For example, what is the idea behind ```rewriteMatrixMatrixMultiplication```. Thanks a lot.

**Comment by seibert** [comment]
Good question.  We've changed the lowering strategy in the past few months, so I need to go update our docs to reflect it.  Give me a few days, and I can get a clearer explanation online.

**Comment by chelini** [comment]
Perfect, thanks. Also a simple example on how Matmul is lowered is really appreciated!!
